Repository voxpupuli/beaker_puppet_helpers, pull requests merged in 2025-03, with the labels that each got.

#56 Implement OpenVox support
  lib/beaker_puppet_helpers/install_utils.rb
Labels: enhancement

#57 Drop support for nightly repos
  lib/beaker_puppet_helpers/install_utils.rb
Labels: backwards-incompatible

#59 Release 2.0.0
  CHANGELOG.md
  beaker_puppet_helpers.gemspec
Labels: skip-changelog

#60 Add helper to get agent package name based on collection
  lib/beaker_puppet_helpers/install_utils.rb
Labels: enhancement

#61 Release 2.1.0
  CHANGELOG.md
  beaker_puppet_helpers.gemspec
Labels: skip-changelog

#62 Support the none collection in implementation helpers
  lib/beaker_puppet_helpers/install_utils.rb
Labels: enhancement
